@extends('layouts.app')
@section('title')
Alerts
@endsection
@section('content')
@include('pages.alerts.left_accent')
@include('pages.alerts.top_accent')
@include('pages.alerts.banner')
@include('pages.alerts.traditional')
@endsection
